name: Send Daily Email

on:
  schedule:
    - cron: '0 8 * * *' # Every day at 8 AM UTC

jobs:
  send-email:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install email sqlite3

      - name: Run email script
        run: |
          python send_email.py
